1. Signal Classification Using Machine Learning
Problem Statement: You have a dataset of electrical signals, where each signal
represents either a &quot;sine wave&quot; or a &quot;square wave.&quot; The dataset contains the following
features for each signal: - Amplitude (in volts) , Frequency (in Hz) , Duration (in
seconds) , Peak-to-Peak Voltage (in volts) .
Your task is to develop a machine learning model that can classify each signal as
either &quot;Sine&quot; or &quot;Square&quot; based on these features using KNN. Encode labels (Sine →
0, Square → 1)

S.No  Amplitude Frequency  Duration    Peak-to-Peak   Label
1 1 50 1 2 Sine

2 1.5 60 0.5 3 Squar
e

3 0.8 55 1.2 1.6 Sine

4 2 40 1 4 Squar
e

5 1.2 65 0.8 2.4 Sine

6 1.7 45 1.5 3.4 Squar
e

7 0.9 70 1 1.8 Sine

8 2.1 35 1.3 4.2 Squar
e

9 1.1 60 0.9 2.2 Sine

10 1.8 48 1 3.6 Squar
e

11 0.95 62 1.1 1.9 Sine

12 2.2 42 0.7 4.4 Squar
e

13 1 58 1 2 Sine

14 1.9 46 1.2 3.8 Square

15 1.3 66 0.6 2.6 Sine

In [1]:
import pandas as pd

data = {
    'S.No': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    'Amplitude': [1, 1.5, 0.8, 2, 1.2, 1.7, 0.9, 2.1, 1.1, 1.8, 0.95, 2.2, 1, 1.9, 1.3],
    'Frequency': [50, 60, 55, 40, 65, 45, 70, 35, 60, 48, 62, 42, 58, 46, 66],
    'Duration': [1, 0.5, 1.2, 1, 0.8, 1.5, 1, 1.3, 0.9, 1, 1.1, 0.7, 1, 1.2, 0.6],
    'Peak-to-Peak': [2, 3, 1.6, 4, 2.4, 3.4, 1.8, 4.2, 2.2, 3.6, 1.9, 4.4, 2, 3.8, 2.6],
    'Label': ['Sine', 'Square', 'Sine', 'Square', 'Sine', 'Square', 'Sine', 'Square', 'Sine', 'Square', 'Sine', 'Square', 'Sine', 'Square', 'Sine']
}

df = pd.DataFrame(data)
display(df.head())

   S.No  Amplitude  Frequency  Duration  Peak-to-Peak   Label
0     1        1.0         50       1.0           2.0    Sine
1     2        1.5         60       0.5           3.0  Square
2     3        0.8         55       1.2           1.6    Sine
3     4        2.0         40       1.0           4.0  Square
4     5        1.2         65       0.8           2.4    Sine

In [2]:
# Encode labels (Sine -> 0, Square -> 1)
df['Label_encoded'] = df['Label'].map({'Sine': 0, 'Square': 1})
display(df.head())

   S.No  Amplitude  Frequency  Duration  Peak-to-Peak   Label  Label_encoded
0     1        1.0         50       1.0           2.0    Sine              0
1     2        1.5         60       0.5           3.0  Square              1
2     3        0.8         55       1.2           1.6    Sine              0
3     4        2.0         40       1.0           4.0  Square              1
4     5        1.2         65       0.8           2.4    Sine              0

In [3]:
# Define features (X) and target (y)
X = df[['Amplitude', 'Frequency', 'Duration', 'Peak-to-Peak']]
y = df['Label_encoded']

print("Features (X) shape:", X.shape)
print("Target (y) shape:", y.shape)

Features (X) shape: (15, 4)
Target (y) shape: (15,)

In [4]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (12, 4)
X_test shape: (3, 4)
y_train shape: (12,)
y_test shape: (3,)

In [5]:
from sklearn.preprocessing import StandardScaler

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler on the training data and transform both training and test data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("X_train_scaled shape:", X_train_scaled.shape)
print("X_test_scaled shape:", X_test_scaled.shape)

X_train_scaled shape: (12, 4)
X_test_scaled shape: (3, 4)

In [6]:
from sklearn.neighbors import KNeighborsClassifier

# Initialize the KNN classifier
knn = KNeighborsClassifier(n_neighbors=3) # Using k=3 as a common starting point

# Train the model using the scaled training data
knn.fit(X_train_scaled, y_train)

print("KNN model trained successfully with k=", knn.n_neighbors)

KNN model trained successfully with k= 3