2. Write a program to classify a component is defective or not based on Voltage and
Current using KNN. Encode labels (Working → 1, Defective → 1)

Voltage
(V) Current (A) Status

5 0.5 Working

5.5 0.4 Working

4.8 0.6 Working

6 0.3 Defective

6.5 0.2 Defective

6.2 0.25 Defective

4.9 0.55 Working

5.8 0.35 Defective

5.2 0.5 Working

6.3 0.22 Defective

In [8]:
import pandas as pd

# Data for the second problem
data_component = {
    'Voltage': [5, 5.5, 4.8, 6, 6.5, 6.2, 4.9, 5.8, 5.2, 6.3],
    'Current': [0.5, 0.4, 0.6, 0.3, 0.2, 0.25, 0.55, 0.35, 0.5, 0.22],
    'Status': ['Working', 'Working', 'Working', 'Defective', 'Defective', 'Defective', 'Working', 'Defective', 'Working', 'Defective']
}

df_component = pd.DataFrame(data_component)
display(df_component.head())

   Voltage  Current     Status
0      5.0      0.5    Working
1      5.5      0.4    Working
2      4.8      0.6    Working
3      6.0      0.3  Defective
4      6.5      0.2  Defective

In [9]:
# Encode labels (Working -> 0, Defective -> 1)
df_component['Status_encoded'] = df_component['Status'].map({'Working': 0, 'Defective': 1})
display(df_component.head())

   Voltage  Current     Status  Status_encoded
0      5.0      0.5    Working               0
1      5.5      0.4    Working               0
2      4.8      0.6    Working               0
3      6.0      0.3  Defective               1
4      6.5      0.2  Defective               1

In [10]:
# Define features (X_component) and target (y_component) for the component classification
X_component = df_component[['Voltage', 'Current']]
y_component = df_component['Status_encoded']

print("Features (X_component) shape:", X_component.shape)
print("Target (y_component) shape:", y_component.shape)

Features (X_component) shape: (10, 2)
Target (y_component) shape: (10,)

In [11]:
from sklearn.model_selection import train_test_split

# Split the component data into training and testing sets
X_comp_train, X_comp_test, y_comp_train, y_comp_test = train_test_split(X_component, y_component, test_size=0.3, random_state=42)

print("X_comp_train shape:", X_comp_train.shape)
print("X_comp_test shape:", X_comp_test.shape)
print("y_comp_train shape:", y_comp_train.shape)
print("y_comp_test shape:", y_comp_test.shape)

X_comp_train shape: (7, 2)
X_comp_test shape: (3, 2)
y_comp_train shape: (7,)
y_comp_test shape: (3,)

In [12]:
from sklearn.preprocessing import StandardScaler

# Initialize the StandardScaler for component data
scaler_comp = StandardScaler()

# Fit and transform the training data, then transform the test data
X_comp_train_scaled = scaler_comp.fit_transform(X_comp_train)
X_comp_test_scaled = scaler_comp.transform(X_comp_test)

print("X_comp_train_scaled shape:", X_comp_train_scaled.shape)
print("X_comp_test_scaled shape:", X_comp_test_scaled.shape)

X_comp_train_scaled shape: (7, 2)
X_comp_test_scaled shape: (3, 2)

In [13]:
from sklearn.neighbors import KNeighborsClassifier

# Initialize the KNN classifier for component data
knn_comp = KNeighborsClassifier(n_neighbors=3) # Using k=3 as a starting point

# Train the model using the scaled training data
knn_comp.fit(X_comp_train_scaled, y_comp_train)

print("KNN model for components trained successfully with k=", knn_comp.n_neighbors)

KNN model for components trained successfully with k= 3